# Generated by Django 2.2.3 on 2020-09-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='company_id',
            field=models.CharField(default='Not Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='company_tin',
            field=models.CharField(default='Not Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='department',
            field=models.CharField(default='Not Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='designation',
            field=models.CharField(default='Not Available', max_length=50),
        ),
    ]
