# Generated by Django 2.2.3 on 2020-09-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='biometrics_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
