# Generated by Django 2.2.3 on 2020-09-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200922_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleaves',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Disapproved', 'Disapproved'), ('Approved', 'Approved')], default='Pending', max_length=150),
        ),
    ]
