# Generated by Django 2.2.3 on 2020-09-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200923_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleaves',
            name='balance_as_of_this_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeeleaves',
            name='leave_credits',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='employeeleaves',
            name='less_this_application',
            field=models.IntegerField(),
        ),
    ]
