# Generated by Django 2.2.3 on 2020-09-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20200923_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='sick_leave_credits',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vacation_leave_credits',
            field=models.IntegerField(default=7),
        ),
    ]
