# Generated by Django 2.2.3 on 2020-09-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200923_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='sick_leave_credits',
            field=models.IntegerField(blank=True, default=7),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='vacation_leave_credits',
            field=models.IntegerField(blank=True, default=7),
        ),
    ]
