# Generated by Django 2.2.3 on 2020-09-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20200923_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleaves',
            name='balance_as_of_this_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeeleaves',
            name='leave_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeeleaves',
            name='less_this_application',
            field=models.IntegerField(default=0),
        ),
    ]
