# Generated by Django 2.2.3 on 2020-09-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20200924_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleaves',
            name='has_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeleaves',
            name='remarks',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeleaves',
            name='classification_of_leave',
            field=models.CharField(choices=[('Bereavement Leave', 'Bereavement Leave'), ('Vacation Leave', 'Vacation Leave'), ('Maternity Leave', 'Maternity Leave'), ('Sick Leave', 'Sick Leave'), ('Paternity Leave', 'Paternity Leave'), ('Leave without pay', 'Leave without pay')], default='Bereavement Leave', max_length=100),
        ),
    ]
