# Generated by Django 2.2.3 on 2020-09-25 01:15

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20200924_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleaves',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', validators=[application.models.file_validator2], verbose_name='Resume/Curriculum Vitae (Optional):'),
        ),
    ]
