# Generated by Django 2.2.3 on 2020-09-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20200925_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='preffered_working_hours',
            field=models.CharField(choices=[('1', '8:00am-5:00pm'), ('2', '8:30am-5:30pm'), ('3', '9:00am-6:00pm')], default='1', max_length=100),
        ),
    ]
