# Generated by Django 2.2.3 on 2020-10-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_companyinfo_preffered_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='preffered_working_hours',
            field=models.CharField(choices=[('8:00am-5:00pm', '8:00am-5:00pm'), ('8:30am-5:30pm', '8:30am-5:30pm'), ('9:00am-6:00pm', '9:00am-6:00pm')], default='8:00am-5:00pm', max_length=100),
        ),
    ]
