# Generated by Django 2.2.3 on 2020-10-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20201012_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinfo',
            name='holiday',
            field=models.CharField(choices=[('Regulary Day', 'Regulary Day'), ('New Year’s Day', 'New Year’s Day'), ('Araw ng Kagitingan', 'Araw ng Kagitingan'), ('Maundy Thursday', 'Maundy Thursday'), ('Good Friday', 'Good Friday'), ('Labor Day', 'Labor Day'), ('Independence Day', 'Independence Day'), ('National Heroes’ Day', 'National Heroes’ Day'), ('Bonifacio Day', 'Bonifacio Day'), ('Christmas Day', 'Christmas Day'), ('Rizal Day', 'Rizal Day')], default='No Holiday', max_length=100),
        ),
    ]
