# Generated by Django 2.2.3 on 2020-10-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20201020_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinfo',
            name='holiday',
            field=models.CharField(choices=[('No Holiday', 'No Holiday'), ('Regular Holiday', 'Regular Holiday'), ('Special Holiday', 'Special Holiday')], default='No Holiday', max_length=100),
        ),
    ]
