# Generated by Django 2.2.3 on 2020-10-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_auto_20201020_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeepayroll',
            old_name='late_or_absences',
            new_name='holiday_pay',
        ),
        migrations.RenameField(
            model_name='employeepayroll',
            old_name='overtime_pay',
            new_name='ot_pay',
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='absences',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='late_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='ot_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='undertime_min',
            field=models.IntegerField(default=0),
        ),
    ]
