# Generated by Django 2.2.3 on 2020-10-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20201026_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayroll',
            name='absences_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='late_undertime_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
