# Generated by Django 3.1.2 on 2020-11-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_rolespermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolespermission',
            name='role',
            field=models.CharField(choices=[('Managing Directory', 'Managing Directory'), ('Human Resource', 'Human Resource'), ('Business Unit Head', 'Business Unit Head'), ('Employee', 'Employee')], default='Managing Directory', max_length=200),
        ),
        migrations.AlterField(
            model_name='rolespermission',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
