# Generated by Django 3.1.2 on 2020-11-10 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_auto_20201110_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolespermission',
            name='employee_ci_rp_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ci_rp_fk_r', to='application.companyinfo'),
        ),
    ]
