# Generated by Django 3.1.2 on 2020-11-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_auto_20201110_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolespermission',
            name='role',
            field=models.CharField(choices=[('Managing Director', 'Managing Director'), ('Human Resource', 'Human Resource'), ('Business Unit Head', 'Business Unit Head'), ('Employee', 'Employee')], default='Managing Director', max_length=200),
        ),
    ]
