# Generated by Django 3.1.2 on 2020-12-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_auto_20201111_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
