# Generated by Django 2.2.3 on 2020-07-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0043_auto_20200628_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinfo',
            name='overtime',
            field=models.IntegerField(default=0),
        ),
    ]
