# Generated by Django 2.2.3 on 2020-07-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0045_auto_20200709_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceinfo',
            name='payment_computation_for_work_done',
        ),
        migrations.RemoveField(
            model_name='attendanceinfo',
            name='payment_computation_overtime',
        ),
        migrations.AddField(
            model_name='attendanceinfo',
            name='has_itenerary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendanceinfo',
            name='has_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendanceinfo',
            name='overtime_category',
            field=models.CharField(choices=[('No Overtime', 'No Overtime'), ('Regular Day', 'Regular Day'), ('Rest Day', 'Rest Day')], default='No Overtime', max_length=100),
        ),
    ]
