# Generated by Django 2.2.3 on 2020-07-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0047_attendanceinfo_holiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepayroll',
            name='legal_holiday',
        ),
        migrations.RemoveField(
            model_name='employeepayroll',
            name='monthly_allowance',
        ),
        migrations.RemoveField(
            model_name='employeepayroll',
            name='monthly_rate',
        ),
        migrations.RemoveField(
            model_name='employeepayroll',
            name='special_holiday',
        ),
    ]
