# Generated by Django 2.2.3 on 2020-07-14 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0048_auto_20200712_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('date_filed', models.DateField(auto_now_add=True)),
                ('day', models.CharField(max_length=200)),
                ('re_sp_ot', models.CharField(choices=[('Regulary Day', 'Regulary Day'), ('Rest Day', 'Rest Day'), ('Special Day', 'Special Day')], default='Regulary Day', max_length=100)),
                ('date_rendered', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
                ('product', models.CharField(max_length=200)),
                ('timeIn', models.CharField(max_length=100)),
                ('timeOut', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('employee_overtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_overtime', to='application.EmployeeItenerary')),
            ],
        ),
    ]
