# Generated by Django 2.2.3 on 2020-07-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0049_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='overtime',
            name='checked_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='overtime',
            name='noted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
