# Generated by Django 2.2.3 on 2020-07-14 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0050_auto_20200714_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='employee_overtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_overtime', to='application.PersonalInfo'),
        ),
    ]
