# Generated by Django 2.2.3 on 2020-07-14 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0051_auto_20200714_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overtime',
            old_name='department',
            new_name='departments',
        ),
    ]
