# Generated by Django 2.2.3 on 2020-07-14 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0053_auto_20200714_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime',
            name='date_rendered',
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='day',
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='description',
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='product',
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='re_sp_ot',
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='timeIn',
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='timeOut',
        ),
        migrations.CreateModel(
            name='OvertimeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rendered', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=200)),
                ('re_sp_ot', models.CharField(choices=[('Regulary Day', 'Regulary Day'), ('Rest Day', 'Rest Day'), ('Special Day', 'Special Day')], default='Regulary Day', max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('product', models.CharField(max_length=200)),
                ('timeIn', models.CharField(max_length=100)),
                ('timeOut', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('overtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime', to='application.PersonalInfo')),
            ],
        ),
    ]
