# Generated by Django 2.2.3 on 2020-07-14 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0054_auto_20200714_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimedetails',
            name='overtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime', to='application.Overtime'),
        ),
    ]
