# Generated by Django 2.2.3 on 2020-07-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0056_auto_20200715_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimedetails',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
